/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.fmp.lojaroupas.view;
import br.com.fmp.lojaroupas.dao.FornecedorDAO;
import br.com.fmp.lojaroupas.dao.PedidoDAO;
import br.com.fmp.lojaroupas.model.Fornecedor;
import br.com.fmp.lojaroupas.model.Pedido;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author erikf
 */
public class TelaPedidos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPedidos.class.getName());

    /**
     * Creates new form TelaPedidos
     */
    public TelaPedidos() {
        initComponents();
        // --- LÓGICA DE ABERTURA ---
        loadComboBoxFornecedores(); // 1. Carrega os fornecedores no dropdown
        loadComboBoxStatus();       // 2. Carrega "Pendente" / "Completo"
        readJTable();
    }
    
    private void loadComboBoxFornecedores() {
        FornecedorDAO dao = new FornecedorDAO();
        List<Fornecedor> fornecedores = dao.read(); 
  
        cmbFornecedor.removeAllItems(); 
        
        for (Fornecedor f : fornecedores) {
        
            cmbFornecedor.addItem(f); 
        }
    }
  
    private void loadComboBoxStatus() {
        cmbStatus.removeAllItems();
        cmbStatus.setModel(new DefaultComboBoxModel<>(new String[] {
            "Pendente",
            "Completo",
            "Cancelado"
        }));
    }


    public void readJTable() {
        DefaultTableModel modelo = (DefaultTableModel) tblPedidos.getModel();
        modelo.setNumRows(0); 

        PedidoDAO dao = new PedidoDAO(); 
        List<Pedido> pedidos = dao.read(); 

        for (Pedido p : pedidos) { 
            modelo.addRow(new Object[]{ 
                p.getId(),
                p.getFornecedor().getNome(), 
                p.getDataPedido(),
                p.getStatus(),
                p.getValorTotal()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbFornecedor = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cmbStatus = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtValorTotal = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPedidos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Fornecedor:");

        jLabel2.setText("Status:");

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Valor Total:");

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34)
                        .addComponent(cmbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtValorTotal))))
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCadastrar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnExcluir)
                        .addComponent(btnAtualizar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrar))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir))
                .addContainerGap(165, Short.MAX_VALUE))
        );

        tblPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "FORNECEDOR", "DATA PEDIDO", "STATUS", "VALOR TOTAL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPedidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPedidos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

    if (txtValorTotal.getText().trim().isEmpty()) { 
        JOptionPane.showMessageDialog(null, "O campo 'Valor Total' não pode estar vazio.");
        return;
    }
    
    Pedido p = new Pedido(); 
   
    p.setFornecedor((Fornecedor) cmbFornecedor.getSelectedItem()); 
    p.setStatus((String) cmbStatus.getSelectedItem());
    p.setValorTotal(Double.parseDouble(txtValorTotal.getText()));
    p.setDataPedido(new Date());
    
    PedidoDAO dao = new PedidoDAO(); 
    dao.create(p); 

    txtValorTotal.setText("");
   
    readJTable();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // 1. Verifica se o usuário realmente selecionou uma linha
    if (tblPedidos.getSelectedRow() == -1) { 
        JOptionPane.showMessageDialog(null, "Selecione um pedido para atualizar.");
        return;
    }
    
    // 2. Validação
    if (txtValorTotal.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "O campo 'Valor Total' não pode estar vazio.");
        return; 
    }

    // 3. Cria o objeto Pedido
    Pedido p = new Pedido(); 
    
    // 4. Pega o ID da tabela (para o UPDATE saber QUAL linha mudar)
    p.setId((int) tblPedidos.getValueAt(tblPedidos.getSelectedRow(), 0));
    
    // 5. Pega os dados atualizados dos campos
    p.setFornecedor((Fornecedor) cmbFornecedor.getSelectedItem()); 
    p.setStatus((String) cmbStatus.getSelectedItem());
    p.setValorTotal(Double.parseDouble(txtValorTotal.getText()));
    
    // 6. Pega a DATA da tabela (para não alterar a data original)
    p.setDataPedido((Date) tblPedidos.getValueAt(tblPedidos.getSelectedRow(), 2));

    // 7. Chama o DAO de ATUALIZAÇÃO (UPDATE)
    PedidoDAO dao = new PedidoDAO(); 
    dao.update(p); 

    // 8. Limpa os campos
    txtValorTotal.setText("");

    // 9. Atualiza a tabela
    readJTable();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
       // 1. Verifica se selecionou uma linha
    if (tblPedidos.getSelectedRow() == -1) {
        JOptionPane.showMessageDialog(null, "Selecione um pedido para excluir.");
        return;
    }

    int id = (int) tblPedidos.getValueAt(tblPedidos.getSelectedRow(), 0);

    PedidoDAO dao = new PedidoDAO();
    dao.delete(id); 
    
    txtValorTotal.setText("");
    cmbFornecedor.setSelectedIndex(0);
    cmbStatus.setSelectedIndex(0);

    readJTable();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void tblPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPedidosMouseClicked

    if (tblPedidos.getSelectedRow() != -1) { 
      
        String nomeFornecedor = tblPedidos.getValueAt(tblPedidos.getSelectedRow(), 1).toString();
 
        for (int i = 0; i < cmbFornecedor.getItemCount(); i++) {
            Fornecedor f = (Fornecedor) cmbFornecedor.getItemAt(i);
            if (f.getNome().equals(nomeFornecedor)) {
                cmbFornecedor.setSelectedIndex(i);
                break;
            }
        }
        
        String status = tblPedidos.getValueAt(tblPedidos.getSelectedRow(), 3).toString();
        // Loop para achar o STATUS no ComboBox
        for (int i = 0; i < cmbStatus.getItemCount(); i++) {
            String s = (String) cmbStatus.getItemAt(i);
            if (s.equals(status)) {
                cmbStatus.setSelectedIndex(i);
                break;
            }
        }
        txtValorTotal.setText(tblPedidos.getValueAt(tblPedidos.getSelectedRow(), 4).toString());
    }
    }//GEN-LAST:event_tblPedidosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // A linha mais importante:
                new TelaPedidos().setVisible(true); // <-- MUDOU
            }
        });
        java.awt.EventQueue.invokeLater(() -> new TelaPedidos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JComboBox<Fornecedor> cmbFornecedor;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPedidos;
    private javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables
}
